import "@/styles/globals.css";
import "bulma/css/bulma.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
// import Providers from "@/providers/provider";
import SupabaseProvider from "../providers/SupaBaseProvider";
import UserProvider from "@/providers/useProvider";

import ToasterProvider from "@/providers/ToasterProvider";
export const dynamic = "force-dynamic";
const inter = Open_Sans({
  subsets: ["latin"],
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "Wytrenowani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <head>
        {" "}
        <meta charSet="UTF-8" />
      </head>

      <body className={inter.className}>
        <div className="gradient-bg text-white">
          <SupabaseProvider>
            <UserProvider>{children}</UserProvider>
          </SupabaseProvider>
        </div>{" "}
      </body>
    </html>
  );
}
