import "@/styles/globals.css";
import "bulma/css/bulma.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
// import Providers from "@/providers/provider";
import SupabaseProvider from "../providers/SupaBaseProvider";
import UserProvider from "@/providers/useProvider";

import ToasterProvider from "@/providers/ToasterProvider";
export const dynamic = "force-dynamic";
const inter = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Wytrenowani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl">
      <head>
        {" "}
        <meta charSet="UTF-8" />
      </head>

      <body className={inter.className}>
        {" "}
        <div className="gradient-bg  ">
          <div className="gradients-container  dark:bg-secondary">
            <div className="g1"></div>
          </div>{" "}
        </div>{" "}
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>{children}</UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
